import "./globals.css";
import { Inter } from "next/font/google";
import { twMerge as cn } from "tailwind-merge";
import { themeEffect } from "./docs/components/theme-effect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: `(${themeEffect.toString()})();` }}
        />
      </head>

      <body
        className={cn(
          inter.className,
          "bg-geist-background text-geist-foreground"
        )}
      >
        {children}
      </body>
    </html>
  );
}
