import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getTheme } from "@/lib/get-theme";
import { cn } from "@/lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        inter.className,
        "bg-geist-background text-geist-foreground"
      )}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: `(${getTheme.toString()})();` }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
